using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MeetUpBeat : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        StartCoroutine(LeftArrow(0.00f));
        StartCoroutine(UpArrow(0.46f));
        StartCoroutine(RightArrow(0.88f));
        StartCoroutine(DownArrow(1.24f));
        StartCoroutine(LeftArrow(1.59f));
        StartCoroutine(UpArrow(2.04f));
        StartCoroutine(RightArrow(2.30f));
        StartCoroutine(DownArrow(2.54f));
        StartCoroutine(LeftArrow(2.74f));
        StartCoroutine(UpArrow(3.00f));
        StartCoroutine(RightArrow(3.22f));
        StartCoroutine(DownArrow(3.45f));
        StartCoroutine(LeftArrow(3.70f));
        StartCoroutine(UpArrow(4.15f));
        StartCoroutine(RightArrow(4.60f));
        StartCoroutine(DownArrow(5.02f));
        StartCoroutine(LeftArrow(5.35f));
        StartCoroutine(UpArrow(5.57f));
        StartCoroutine(RightArrow(5.76f));
        StartCoroutine(DownArrow(6.02f));
        StartCoroutine(LeftArrow(6.23f));
        StartCoroutine(UpArrow(6.47f));
        StartCoroutine(RightArrow(6.92f));
        StartCoroutine(RightArrow(7.39f));
        StartCoroutine(UpArrow(7.85f));
        StartCoroutine(LeftArrow(8.33f));
        StartCoroutine(DownArrow(8.68f));
        StartCoroutine(RightArrow(9.01f));
        StartCoroutine(UpArrow(9.45f));
        StartCoroutine(LeftArrow(9.68f));
        StartCoroutine(DownArrow(9.92f));
        StartCoroutine(RightArrow(10.15f));
        StartCoroutine(UpArrow(10.37f));
        StartCoroutine(LeftArrow(10.62f));
        StartCoroutine(DownArrow(11.08f));
        StartCoroutine(RightArrow(11.55f));
        StartCoroutine(UpArrow(12.01f));
        StartCoroutine(LeftArrow(12.36f));
        StartCoroutine(DownArrow(12.69f));
        StartCoroutine(RightArrow(12.93f));
        StartCoroutine(UpArrow(13.13f));
        StartCoroutine(LeftArrow(13.38f));
        StartCoroutine(DownArrow(13.60f));
        StartCoroutine(RightArrow(13.84f));
        StartCoroutine(UpArrow(14.30f));
        StartCoroutine(UpArrow(14.78f));
        StartCoroutine(RightArrow(15.22f));
        StartCoroutine(DownArrow(15.68f));
        StartCoroutine(LeftArrow(16.04f));
        StartCoroutine(UpArrow(16.37f));
        StartCoroutine(RightArrow(16.84f));
        StartCoroutine(DownArrow(17.09f));
        StartCoroutine(LeftArrow(17.29f));
        StartCoroutine(UpArrow(17.52f));
        StartCoroutine(RightArrow(17.75f));
        StartCoroutine(DownArrow(17.98f));
        StartCoroutine(LeftArrow(18.20f));
        StartCoroutine(UpArrow(18.49f));
        StartCoroutine(RightArrow(18.92f));
        StartCoroutine(DownArrow(19.36f));
        StartCoroutine(LeftArrow(19.74f));
        StartCoroutine(UpArrow(20.06f));
        StartCoroutine(RightArrow(20.29f));
        StartCoroutine(DownArrow(20.51f));
        StartCoroutine(LeftArrow(20.74f));
        StartCoroutine(UpArrow(20.97f));
        StartCoroutine(RightArrow(21.22f));
        StartCoroutine(DownArrow(21.67f));
        StartCoroutine(DownArrow(22.15f));
        StartCoroutine(RightArrow(22.60f));
        StartCoroutine(UpArrow(23.05f));
        StartCoroutine(LeftArrow(23.42f));
        StartCoroutine(DownArrow(23.78f));
        StartCoroutine(RightArrow(24.22f));
        StartCoroutine(UpArrow(24.44f));
        StartCoroutine(LeftArrow(24.66f));
        StartCoroutine(DownArrow(24.93f));
        StartCoroutine(RightArrow(25.14f));
        StartCoroutine(UpArrow(25.37f));
        StartCoroutine(UpArrow(25.83f));
        StartCoroutine(LeftArrow(26.29f));
        StartCoroutine(DownArrow(26.78f));
        StartCoroutine(RightArrow(27.10f));
        StartCoroutine(UpArrow(27.44f));
        StartCoroutine(LeftArrow(27.68f));
        StartCoroutine(DownArrow(27.94f));
        StartCoroutine(RightArrow(28.16f));
        StartCoroutine(UpArrow(28.37f));
        StartCoroutine(LeftArrow(28.62f));
        StartCoroutine(DownArrow(29.08f));
        StartCoroutine(DownArrow(29.56f));
        StartCoroutine(RightArrow(30.02f));
        StartCoroutine(UpArrow(30.44f));
        StartCoroutine(LeftArrow(30.78f));
        StartCoroutine(DownArrow(31.13f));
        StartCoroutine(DownArrow(31.40f));
        StartCoroutine(RightArrow(31.62f));
        StartCoroutine(UpArrow(31.85f));
        StartCoroutine(LeftArrow(32.06f));
        StartCoroutine(DownArrow(32.32f));
        StartCoroutine(DownArrow(32.77f));
        StartCoroutine(DownArrow(33.25f));
        StartCoroutine(LeftArrow(33.73f));
        StartCoroutine(UpArrow(34.13f));
        StartCoroutine(RightArrow(34.46f));
        StartCoroutine(DownArrow(34.83f));
        StartCoroutine(LeftArrow(35.09f));
        StartCoroutine(UpArrow(35.30f));
        StartCoroutine(RightArrow(35.53f));
        StartCoroutine(DownArrow(35.76f));
        StartCoroutine(LeftArrow(36.00f));
        StartCoroutine(UpArrow(36.46f));
        StartCoroutine(UpArrow(36.95f));
        StartCoroutine(LeftArrow(37.41f));
        StartCoroutine(DownArrow(37.86f));
        StartCoroutine(RightArrow(38.10f));
        StartCoroutine(UpArrow(38.31f));
        StartCoroutine(LeftArrow(38.54f));
        StartCoroutine(DownArrow(38.79f));
        StartCoroutine(RightArrow(38.99f));
        StartCoroutine(UpArrow(39.22f));
        StartCoroutine(LeftArrow(39.45f));
        StartCoroutine(DownArrow(39.70f));
        StartCoroutine(RightArrow(40.17f));
        StartCoroutine(RightArrow(40.65f));
        StartCoroutine(DownArrow(41.07f));
        StartCoroutine(LeftArrow(41.51f));
        StartCoroutine(UpArrow(41.85f));
        StartCoroutine(RightArrow(42.22f));
        StartCoroutine(DownArrow(42.47f));
        StartCoroutine(LeftArrow(42.70f));
        StartCoroutine(UpArrow(42.93f));
        StartCoroutine(RightArrow(43.12f));
        StartCoroutine(DownArrow(43.41f));
        StartCoroutine(LeftArrow(43.85f));
         
        StartCoroutine(UpArrow(44.34f));
        StartCoroutine(LeftArrow(44.80f));
        StartCoroutine(DownArrow(45.25f));
        StartCoroutine(RightArrow(45.58f));
        StartCoroutine(UpArrow(45.94f));
        StartCoroutine(LeftArrow(46.17f));
        StartCoroutine(LeftArrow(46.65f));
        StartCoroutine(LeftArrow(47.10f));
        StartCoroutine(LeftArrow(47.57f));
        StartCoroutine(DownArrow(48.02f));
        StartCoroutine(RightArrow(48.50f));
        StartCoroutine(UpArrow(48.95f));
        StartCoroutine(LeftArrow(49.31f));
        StartCoroutine(DownArrow(49.64f));
        StartCoroutine(DownArrow(49.88f));
        StartCoroutine(DownArrow(50.30f));
        StartCoroutine(DownArrow(50.79f));
        StartCoroutine(DownArrow(51.22f));
        StartCoroutine(DownArrow(51.71f));
        StartCoroutine(RightArrow(52.17f));
        StartCoroutine(UpArrow(52.61f));
        StartCoroutine(LeftArrow(52.95f));
        StartCoroutine(DownArrow(53.30f));
        StartCoroutine(RightArrow(53.55f));
        StartCoroutine(RightArrow(54.01f));
        StartCoroutine(RightArrow(54.46f));
        StartCoroutine(RightArrow(54.94f));
        StartCoroutine(UpArrow(55.42f));
        StartCoroutine(LeftArrow(55.89f));
        StartCoroutine(DownArrow(56.31f));
        StartCoroutine(RightArrow(56.65f));
        StartCoroutine(UpArrow(56.98f));
        StartCoroutine(UpArrow(57.25f));
        StartCoroutine(UpArrow(57.72f));
        StartCoroutine(UpArrow(58.18f));
        StartCoroutine(UpArrow(58.62f));

        StartCoroutine(LeftArrow(59.09f));
        StartCoroutine(DownArrow(59.57f));
        StartCoroutine(RightArrow(60.01f));
        StartCoroutine(UpArrow(60.36f));
        StartCoroutine(LeftArrow(60.71f));
        StartCoroutine(DownArrow(61.19f));
        StartCoroutine(RightArrow(61.42f));
        StartCoroutine(UpArrow(61.64f));
        StartCoroutine(LeftArrow(61.87f));
        StartCoroutine(DownArrow(62.33f));
        StartCoroutine(DownArrow(62.78f));
        StartCoroutine(LeftArrow(63.25f));
        StartCoroutine(UpArrow(63.71f));
        StartCoroutine(RightArrow(64.05f));
        StartCoroutine(DownArrow(64.37f));
        StartCoroutine(DownArrow(64.87f));
        StartCoroutine(LeftArrow(65.11f));
        StartCoroutine(UpArrow(65.33f));
        StartCoroutine(RightArrow(65.55f));
        StartCoroutine(DownArrow(65.79f));
        StartCoroutine(LeftArrow(65.99f));
        StartCoroutine(UpArrow(66.23f));
        StartCoroutine(RightArrow(66.48f));
        StartCoroutine(UpArrow(66.95f));
        StartCoroutine(LeftArrow(67.40f));
        StartCoroutine(DownArrow(67.75f));
        StartCoroutine(RightArrow(68.11f));
        StartCoroutine(UpArrow(68.32f));
        StartCoroutine(LeftArrow(68.55f));
        StartCoroutine(DownArrow(68.81f));
        StartCoroutine(RightArrow(69.00f));
        StartCoroutine(UpArrow(69.24f));
        StartCoroutine(UpArrow(69.68f));
        StartCoroutine(RightArrow(70.16f));
        StartCoroutine(DownArrow(70.62f));
        StartCoroutine(LeftArrow(71.09f));
        StartCoroutine(UpArrow(71.42f));
        StartCoroutine(RightArrow(71.77f));
        StartCoroutine(RightArrow(72.23f));
        StartCoroutine(UpArrow(72.45f));
        StartCoroutine(LeftArrow(72.67f));
        StartCoroutine(DownArrow(72.91f));
        StartCoroutine(RightArrow(73.14f));
        StartCoroutine(UpArrow(73.39f));
        StartCoroutine(UpArrow(73.85f));
        StartCoroutine(LeftArrow(74.32f));
        StartCoroutine(DownArrow(74.75f));
        StartCoroutine(RightArrow(75.09f));
        StartCoroutine(UpArrow(75.45f));
        StartCoroutine(LeftArrow(75.71f));
        StartCoroutine(DownArrow(75.94f));
        StartCoroutine(RightArrow(76.16f));
        StartCoroutine(UpArrow(76.37f));
        StartCoroutine(LeftArrow(76.64f));
        StartCoroutine(DownArrow(77.08f));
        StartCoroutine(DownArrow(77.56f));
        StartCoroutine(LeftArrow(78.02f));
        StartCoroutine(UpArrow(78.46f));
        StartCoroutine(RightArrow(78.80f));
        StartCoroutine(DownArrow(79.14f));
        StartCoroutine(LeftArrow(79.62f));
        StartCoroutine(UpArrow(79.84f));
        StartCoroutine(RightArrow(80.07f));
        StartCoroutine(DownArrow(80.30f));
        StartCoroutine(LeftArrow(80.56f));
        StartCoroutine(UpArrow(80.81f));
        StartCoroutine(RightArrow(81.02f));
        StartCoroutine(DownArrow(81.27f));
        StartCoroutine(DownArrow(81.75f));
        StartCoroutine(RightArrow(82.17f));
        StartCoroutine(UpArrow(82.52f));
        StartCoroutine(LeftArrow(82.89f));
        StartCoroutine(DownArrow(83.13f));
        StartCoroutine(RightArrow(83.33f));
        StartCoroutine(UpArrow(83.58f));
        StartCoroutine(LeftArrow(83.79f));
        StartCoroutine(DownArrow(84.06f));
        StartCoroutine(DownArrow(84.51f));
        StartCoroutine(RightArrow(84.96f));
        StartCoroutine(UpArrow(85.40f));
        StartCoroutine(LeftArrow(85.89f));
        StartCoroutine(DownArrow(86.22f));
        StartCoroutine(RightArrow(86.60f));
        StartCoroutine(RightArrow(87.04f));
        StartCoroutine(UpArrow(87.25f));
        StartCoroutine(LeftArrow(87.46f));
        StartCoroutine(DownArrow(87.71f));
        StartCoroutine(RightArrow(87.92f));
        StartCoroutine(UpArrow(88.17f));
        StartCoroutine(UpArrow(88.62f));
        StartCoroutine(RightArrow(89.10f));
        StartCoroutine(DownArrow(89.56f));
        StartCoroutine(LeftArrow(89.91f));
        StartCoroutine(UpArrow(90.24f));
        StartCoroutine(RightArrow(90.49f));
        StartCoroutine(DownArrow(90.71f));
        StartCoroutine(LeftArrow(90.94f));
        StartCoroutine(UpArrow(91.14f));
        StartCoroutine(RightArrow(91.41f));
        StartCoroutine(RightArrow(91.89f));
        //게임종료
        StartCoroutine(GameOver(97f));
    }

    // Update is called once per frame
    public IEnumerator LeftArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject LeftArrow = BeatController.instance.PoolLeft.Get();
    }

    public IEnumerator RightArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject RightArrow = BeatController.instance.PoolRight.Get();
    }

    public IEnumerator UpArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject UptArrow = BeatController.instance.PoolUp.Get();
    }

    public IEnumerator DownArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject DownArrow = BeatController.instance.PoolDown.Get();
    }

    
    public IEnumerator GameOver(float time)
    {
        yield return new WaitForSeconds(time);
        GameManager.instance.ResultUI();
    }
}
