using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WindowBeat : MonoBehaviour
{

    void Start()
    {
        StartCoroutine(UpArrow(0.00f));
        StartCoroutine(UpArrow(0.39f));
        StartCoroutine(UpArrow(0.71f));
        StartCoroutine(UpArrow(1.01f));
        StartCoroutine(LeftArrow(1.35f));
        StartCoroutine(DownArrow(1.51f));
        StartCoroutine(RightArrow(1.85f));
        StartCoroutine(RightArrow(2.72f));
        StartCoroutine(RightArrow(3.05f));
        StartCoroutine(RightArrow(3.36f));
        StartCoroutine(RightArrow(3.68f));
        StartCoroutine(UpArrow(3.99f));
        StartCoroutine(LeftArrow(4.16f));
        StartCoroutine(DownArrow(4.53f));
        StartCoroutine(DownArrow(5.35f));
        StartCoroutine(DownArrow(5.69f));
        StartCoroutine(DownArrow(6.02f));
        StartCoroutine(DownArrow(6.37f));
        StartCoroutine(RightArrow(6.67f));
        StartCoroutine(UpArrow(6.85f));
        StartCoroutine(LeftArrow(7.01f));
        StartCoroutine(DownArrow(7.19f));
        StartCoroutine(RightArrow(7.51f));
        StartCoroutine(UpArrow(7.67f));
        StartCoroutine(LeftArrow(7.83f));
        StartCoroutine(DownArrow(8.02f));
        StartCoroutine(RightArrow(8.35f));
        StartCoroutine(UpArrow(8.69f));
        StartCoroutine(LeftArrow(8.83f));
        StartCoroutine(DownArrow(9.19f));
        StartCoroutine(DownArrow(10.02f));
        StartCoroutine(RightArrow(10.68f));
        StartCoroutine(RightArrow(11.01f));
        StartCoroutine(RightArrow(11.34f));
        StartCoroutine(RightArrow(11.68f));
        StartCoroutine(UpArrow(11.98f));
        StartCoroutine(LeftArrow(12.14f));
        StartCoroutine(DownArrow(12.54f));
        StartCoroutine(RightArrow(12.86f));
        StartCoroutine(UpArrow(13.02f));
        StartCoroutine(LeftArrow(13.14f));
        StartCoroutine(DownArrow(13.35f));
        StartCoroutine(DownArrow(13.68f));
        StartCoroutine(DownArrow(14.02f));
        StartCoroutine(DownArrow(14.36f));
        StartCoroutine(RightArrow(14.66f));
        StartCoroutine(UpArrow(14.82f));
        StartCoroutine(LeftArrow(14.97f));
        StartCoroutine(DownArrow(15.29f));
        StartCoroutine(DownArrow(16.03f));
        StartCoroutine(DownArrow(16.39f));
        StartCoroutine(DownArrow(16.70f));
        StartCoroutine(DownArrow(17.03f));
        StartCoroutine(RightArrow(17.32f));
        StartCoroutine(UpArrow(17.48f));
        StartCoroutine(LeftArrow(17.64f));
        StartCoroutine(DownArrow(17.84f));
        StartCoroutine(RightArrow(18.16f));
        StartCoroutine(UpArrow(18.32f));
        StartCoroutine(LeftArrow(18.48f));
        StartCoroutine(DownArrow(18.68f));
        StartCoroutine(RightArrow(19.02f));
        StartCoroutine(UpArrow(19.34f));
        StartCoroutine(LeftArrow(19.49f));
        StartCoroutine(DownArrow(19.88f));
        StartCoroutine(LeftArrow(21.34f));
        StartCoroutine(LeftArrow(21.69f));
        StartCoroutine(LeftArrow(22.04f));
        StartCoroutine(LeftArrow(22.36f));
        StartCoroutine(UpArrow(22.67f));
        StartCoroutine(RightArrow(22.84f));
        StartCoroutine(DownArrow(23.19f));
        StartCoroutine(DownArrow(24.06f));
        StartCoroutine(DownArrow(24.38f));
        StartCoroutine(DownArrow(24.71f));
        StartCoroutine(DownArrow(25.04f));
        StartCoroutine(LeftArrow(25.38f));
        StartCoroutine(UpArrow(25.73f));
        StartCoroutine(RightArrow(26.09f));
        StartCoroutine(RightArrow(26.73f));
        StartCoroutine(RightArrow(27.05f));
        StartCoroutine(RightArrow(27.39f));
        StartCoroutine(RightArrow(27.69f));
        StartCoroutine(DownArrow(28.04f));
        StartCoroutine(LeftArrow(28.20f));
        StartCoroutine(UpArrow(28.73f));
        StartCoroutine(RightArrow(29.36f));
        StartCoroutine(RightArrow(29.71f));
        StartCoroutine(RightArrow(30.05f));
        StartCoroutine(RightArrow(30.38f));
        StartCoroutine(DownArrow(30.71f));
        StartCoroutine(LeftArrow(31.05f));
        StartCoroutine(UpArrow(31.40f));
        StartCoroutine(UpArrow(32.05f));
        StartCoroutine(UpArrow(32.40f));
        StartCoroutine(LeftArrow(32.77f));
        StartCoroutine(LeftArrow(33.06f));
        StartCoroutine(DownArrow(33.41f));
        StartCoroutine(DownArrow(33.72f));
        StartCoroutine(RightArrow(34.08f));
        StartCoroutine(RightArrow(34.40f));
        StartCoroutine(DownArrow(34.72f));
        StartCoroutine(DownArrow(35.05f));
        StartCoroutine(LeftArrow(35.40f));
        StartCoroutine(LeftArrow(35.72f));
        StartCoroutine(UpArrow(36.07f));
        StartCoroutine(UpArrow(36.39f));
        StartCoroutine(RightArrow(36.73f));
        StartCoroutine(RightArrow(37.07f));
        StartCoroutine(UpArrow(37.42f));
        StartCoroutine(UpArrow(37.73f));
        StartCoroutine(LeftArrow(38.06f));
        StartCoroutine(LeftArrow(38.37f));
        StartCoroutine(DownArrow(38.73f));
        StartCoroutine(DownArrow(39.04f));
        StartCoroutine(RightArrow(39.40f));
        StartCoroutine(RightArrow(39.70f));
        StartCoroutine(UpArrow(40.06f));
        StartCoroutine(UpArrow(40.39f));
        StartCoroutine(LeftArrow(40.73f));
        StartCoroutine(LeftArrow(41.04f));
        StartCoroutine(DownArrow(41.38f));
        StartCoroutine(DownArrow(41.69f));
        StartCoroutine(RightArrow(42.05f));
        StartCoroutine(RightArrow(42.37f));
        StartCoroutine(UpArrow(42.70f));
        StartCoroutine(UpArrow(43.01f));
        StartCoroutine(UpArrow(43.37f));
        StartCoroutine(UpArrow(43.70f));
        StartCoroutine(LeftArrow(44.05f));
        StartCoroutine(LeftArrow(44.38f));
        StartCoroutine(UpArrow(44.73f));
        StartCoroutine(UpArrow(45.03f));
        StartCoroutine(RightArrow(45.37f));
        StartCoroutine(RightArrow(45.70f));
        StartCoroutine(DownArrow(46.04f));
        StartCoroutine(DownArrow(46.35f));
        StartCoroutine(LeftArrow(46.70f));
        StartCoroutine(LeftArrow(47.04f));
        StartCoroutine(DownArrow(47.38f));
        StartCoroutine(DownArrow(47.70f));
        StartCoroutine(RightArrow(48.05f));
        StartCoroutine(RightArrow(48.38f));
        StartCoroutine(DownArrow(48.71f));
        StartCoroutine(DownArrow(49.04f));
        StartCoroutine(RightArrow(49.37f));
        StartCoroutine(RightArrow(49.69f));
        StartCoroutine(UpArrow(50.03f));
        StartCoroutine(UpArrow(50.38f));
        StartCoroutine(LeftArrow(50.72f));
        StartCoroutine(LeftArrow(51.05f));
        StartCoroutine(DownArrow(51.38f));
        StartCoroutine(DownArrow(51.69f));
        StartCoroutine(LeftArrow(52.01f));
        StartCoroutine(LeftArrow(52.34f));
        StartCoroutine(UpArrow(52.69f));
        StartCoroutine(UpArrow(52.99f));

        StartCoroutine(RightArrow(53.32f));
        StartCoroutine(RightArrow(53.67f));
        StartCoroutine(DownArrow(54.00f));
        StartCoroutine(LeftArrow(54.24f));
        StartCoroutine(UpArrow(54.48f));

        StartCoroutine(UpArrow(54.65f));
        StartCoroutine(UpArrow(55.01f));
        StartCoroutine(RightArrow(55.35f));
        StartCoroutine(DownArrow(55.59f));
        StartCoroutine(LeftArrow(55.82f));

        StartCoroutine(DownArrow(56.07f));
        StartCoroutine(DownArrow(56.38f));
        StartCoroutine(RightArrow(56.74f));
        StartCoroutine(UpArrow(57.37f));
        StartCoroutine(UpArrow(57.70f));
        StartCoroutine(LeftArrow(58.05f));

        StartCoroutine(LeftArrow(58.70f));
        StartCoroutine(LeftArrow(59.03f));
        StartCoroutine(UpArrow(59.35f));
        StartCoroutine(RightArrow(59.59f));
        StartCoroutine(DownArrow(59.82f));

        StartCoroutine(RightArrow(60.02f));
        StartCoroutine(RightArrow(60.36f));
        StartCoroutine(UpArrow(60.68f));
        StartCoroutine(LeftArrow(60.93f));
        StartCoroutine(DownArrow(61.14f));

        StartCoroutine(RightArrow(61.35f));
        StartCoroutine(DownArrow(61.63f));
        StartCoroutine(LeftArrow(61.84f));
        StartCoroutine(UpArrow(62.04f));
        StartCoroutine(RightArrow(62.28f));
        StartCoroutine(DownArrow(62.51f));
        StartCoroutine(LeftArrow(62.69f));
        StartCoroutine(UpArrow(63.37f));
        StartCoroutine(RightArrow(63.70f));
        StartCoroutine(DownArrow(64.04f));

        StartCoroutine(DownArrow(64.37f));
        StartCoroutine(DownArrow(64.71f));
        StartCoroutine(DownArrow(65.02f));
        StartCoroutine(LeftArrow(65.35f));
        StartCoroutine(UpArrow(65.53f));
        StartCoroutine(RightArrow(65.88f));
        StartCoroutine(RightArrow(66.68f));
        StartCoroutine(RightArrow(67.02f));
        StartCoroutine(RightArrow(67.36f));
        StartCoroutine(RightArrow(67.67f));
        StartCoroutine(DownArrow(67.99f));
        StartCoroutine(LeftArrow(68.17f));
        StartCoroutine(UpArrow(68.57f));
        StartCoroutine(UpArrow(69.33f));
        StartCoroutine(UpArrow(69.67f));
        StartCoroutine(UpArrow(70.02f));
        StartCoroutine(UpArrow(70.31f));
        StartCoroutine(RightArrow(70.68f));
        StartCoroutine(DownArrow(71.03f));
        StartCoroutine(LeftArrow(71.36f));
        StartCoroutine(UpArrow(72.04f));
        StartCoroutine(UpArrow(72.37f));
        StartCoroutine(LeftArrow(72.71f));
        StartCoroutine(LeftArrow(73.03f));
        StartCoroutine(DownArrow(73.36f));
        StartCoroutine(DownArrow(73.71f));
        StartCoroutine(RightArrow(74.05f));
        StartCoroutine(RightArrow(74.37f));
        StartCoroutine(UpArrow(74.69f));
        StartCoroutine(UpArrow(75.03f));
        StartCoroutine(UpArrow(75.37f));
        StartCoroutine(UpArrow(75.69f));
        StartCoroutine(LeftArrow(76.02f));
        StartCoroutine(DownArrow(76.18f));
        StartCoroutine(RightArrow(76.56f));
        StartCoroutine(RightArrow(77.37f));
        StartCoroutine(RightArrow(77.68f));
        StartCoroutine(RightArrow(78.04f));
        StartCoroutine(RightArrow(78.36f));
        StartCoroutine(UpArrow(78.69f));
        StartCoroutine(LeftArrow(79.01f));
        StartCoroutine(DownArrow(79.38f));
        StartCoroutine(RightArrow(80.04f));
        StartCoroutine(RightArrow(80.37f));
        StartCoroutine(RightArrow(80.70f));
        StartCoroutine(RightArrow(81.05f));
        StartCoroutine(DownArrow(81.35f));
        StartCoroutine(LeftArrow(81.68f));
        StartCoroutine(UpArrow(82.03f));
        StartCoroutine(DownArrow(82.70f));
        StartCoroutine(DownArrow(83.03f));
        StartCoroutine(LeftArrow(83.38f));
        StartCoroutine(UpArrow(83.68f));
        StartCoroutine(RightArrow(84.04f));
        StartCoroutine(DownArrow(84.72f));
        StartCoroutine(RightArrow(85.36f));
        StartCoroutine(RightArrow(85.70f));
        StartCoroutine(RightArrow(86.05f));
        StartCoroutine(RightArrow(86.37f));
        StartCoroutine(UpArrow(86.70f));
        StartCoroutine(LeftArrow(86.86f));
        StartCoroutine(DownArrow(87.20f));
        StartCoroutine(RightArrow(88.09f));
        StartCoroutine(RightArrow(88.38f));
        StartCoroutine(RightArrow(88.70f));
        StartCoroutine(RightArrow(89.04f));

        StartCoroutine(DownArrow(89.35f));
        StartCoroutine(LeftArrow(89.69f));
        StartCoroutine(UpArrow(90.03f));
        StartCoroutine(LeftArrow(90.70f));
        StartCoroutine(LeftArrow(91.02f));
        StartCoroutine(LeftArrow(91.35f));
        StartCoroutine(LeftArrow(91.66f));
        StartCoroutine(DownArrow(92.04f));
        StartCoroutine(RightArrow(92.34f));
        StartCoroutine(UpArrow(92.70f));
        StartCoroutine(DownArrow(93.35f));
        StartCoroutine(DownArrow(93.70f));
        StartCoroutine(LeftArrow(94.05f));
        StartCoroutine(UpArrow(94.37f));
        StartCoroutine(RightArrow(94.70f));
        StartCoroutine(RightArrow(95.38f));
        StartCoroutine(UpArrow(96.02f));
        StartCoroutine(UpArrow(96.36f));
        StartCoroutine(UpArrow(96.69f));
        StartCoroutine(UpArrow(97.03f));
        StartCoroutine(LeftArrow(97.34f));
        StartCoroutine(DownArrow(97.70f));
        StartCoroutine(RightArrow(98.03f));
        StartCoroutine(RightArrow(98.71f));
        StartCoroutine(RightArrow(99.04f));
        StartCoroutine(RightArrow(99.37f));
        StartCoroutine(RightArrow(99.69f));
        StartCoroutine(DownArrow(100.03f));
        StartCoroutine(LeftArrow(100.35f));
        StartCoroutine(UpArrow(100.70f));
        StartCoroutine(RightArrow(101.39f));
        StartCoroutine(RightArrow(101.72f));
        StartCoroutine(RightArrow(102.03f));
        StartCoroutine(RightArrow(102.36f));
        StartCoroutine(UpArrow(102.69f));
        StartCoroutine(LeftArrow(103.02f));
        StartCoroutine(DownArrow(103.37f));
        StartCoroutine(LeftArrow(104.04f));
        StartCoroutine(LeftArrow(104.36f));
        StartCoroutine(UpArrow(104.71f));
        StartCoroutine(UpArrow(105.02f));
        StartCoroutine(RightArrow(105.35f));
        StartCoroutine(RightArrow(105.67f));
        StartCoroutine(DownArrow(106.02f));
        StartCoroutine(DownArrow(106.32f));

        StartCoroutine(UpArrow(106.72f));
        StartCoroutine(UpArrow(107.06f));
        StartCoroutine(LeftArrow(107.39f));
        StartCoroutine(LeftArrow(107.72f));
        StartCoroutine(DownArrow(108.04f));
        StartCoroutine(DownArrow(108.37f));
        StartCoroutine(RightArrow(108.70f));
        StartCoroutine(RightArrow(109.02f));
        StartCoroutine(DownArrow(109.37f));
        StartCoroutine(DownArrow(109.70f));
        StartCoroutine(LeftArrow(110.04f));
        StartCoroutine(LeftArrow(110.36f));
        StartCoroutine(UpArrow(110.71f));
        StartCoroutine(UpArrow(111.04f));
        StartCoroutine(RightArrow(111.39f));
        StartCoroutine(RightArrow(111.72f));
        StartCoroutine(DownArrow(112.08f));
        StartCoroutine(DownArrow(112.40f));
        StartCoroutine(LeftArrow(112.72f));
        StartCoroutine(LeftArrow(113.05f));
        StartCoroutine(UpArrow(113.38f));
        StartCoroutine(UpArrow(113.70f));
        StartCoroutine(RightArrow(114.04f));
        StartCoroutine(RightArrow(114.35f));
        StartCoroutine(UpArrow(114.68f));
        StartCoroutine(UpArrow(115.01f));
        StartCoroutine(LeftArrow(115.36f));
        StartCoroutine(LeftArrow(115.68f));
        StartCoroutine(DownArrow(116.01f));
        StartCoroutine(DownArrow(116.36f));
        StartCoroutine(DownArrow(116.71f));
        StartCoroutine(DownArrow(117.03f));
        //게임 종료
        StartCoroutine(GameOver(122.00f));
    }
    public IEnumerator LeftArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject LeftArrow = BeatController.instance.PoolLeft.Get();
    }

    public IEnumerator RightArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject RightArrow = BeatController.instance.PoolRight.Get();
    }

    public IEnumerator UpArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject UptArrow = BeatController.instance.PoolUp.Get();
    }

    public IEnumerator DownArrow(float time)
    {
        yield return new WaitForSeconds(time);
        GameObject DownArrow = BeatController.instance.PoolDown.Get();
    }

    
    public IEnumerator GameOver(float time)
    {
        yield return new WaitForSeconds(time);
        GameManager.instance.ResultUI();
    }
}
